update NetOrigin 1008
jmanitz/NetOrigin pull request #4
Opened 2020-10-09 04:50 UTC by junli14

add 4 functions and 1 data set, update files

2020-10-15 20:26 UTC, jmanitz commented
* checking package dependencies ... ERROR
Namespace dependency not required: 'corpcor'

2020-10-15 20:34 UTC, jmanitz requested changes
Please rename SIB_model.R and initialize_SIB_model.R. Please edit functions accordingly. 
historically, "SS" is an inappropriate choice

2020-10-15 20:43 UTC, jmanitz requested changes
The other origin detection methods are wrapped within `origin()`. It would be good to align `infer_source_bayesian()` in that framework.

Examples dont require `library(NetOrigin)`, training data should be added according to package structure

2020-10-19 05:01 UTC, junli14 commented
Update on Oct 18

2020-10-22 02:36 UTC, jmanitz approved these changes
looks good as far i can tell

2020-10-22 02:38 UTC, jmanitz approved these changes

2020-10-22 02:38 UTC, jmanitz approved these changes

2020-10-22 02:39 UTC, jmanitz approved these changes

2020-10-22 02:40 UTC, jmanitz requested changes
please do not edit existing code

2020-10-22 02:40 UTC, jmanitz requested changes
please do not edit existing code

2020-10-22 02:40 UTC, jmanitz requested changes
please do not edit existing code

2020-10-22 02:41 UTC, jmanitz approved these changes

2020-10-22 02:41 UTC, jmanitz requested changes
please do not edit existing code

2020-10-22 02:50 UTC, jmanitz approved these changes

2020-10-22 02:51 UTC, jmanitz requested changes
please do not edit existing code

2020-10-31 01:45 UTC, jmanitz approved these changes

2020-10-31 01:46 UTC, merged